# Find slugs on https://github.com/simple-icons/simple-icons/blob/develop/slugs.md
tools:
  Language:
    - html5
    - css
    - sass
    - php
    - javascript
    - typescript
    - nodedotjs
    - rust
    - lua
    - solidity
    - { label: "Nix", icon: "nixos" }
    - graphql
    - mysql
    - mongodb
  Framework:
    - angular
    - react
    - nextdotjs
    - mui
    - redux
    - symfony
    - express
    - nestjs
    - { label: "Doctrine", color: "f4672f" }
    - mongoose
    - { label: "Mikro ORM", color: "0c4346" }
    - { label: "Harhat", color: "fff04d" }
    - { label: "Truffle", color: "5e464d" }
    - ethers
  Infra:
    - { label: "AWS", icon: "task" }
    - googlecloud
    - cloudflare
    - auth0
    - { label: "Docker Swarm", icon: "docker" }
    - kubernetes
    - helm
    - elasticsearch
    - logstash
    - kibana
    - grafana
    - rabbitmq
    - terraform
  Testing:
    - sonarqube
    - { label: "PHPUnit", color: "3f98d3" }
    - jest
    - mocha
    - vitest
    - { label: "Waffle", color: "ffae50" }
    - { label: "Matchstick", color: "120b41" }
  Dev:
    - git
    - github
    - gitlab
    - webstorm
    - { label: "VSCode", color: "007ACC" }
    - neovim
    - debian
    - archlinux
    - nixos
    - npm
    - yarn
    - pnpm
    - bun
    - deno
  CI:
    - githubactions
    - { label: "Gitlab CI", icon: "gitlab" }
    - circleci
    - travisci
    - argo
    - gocd
    - webpack
    - gulp
    - vite
    - swc
    - prettier
    - eslint
