name: Update Activity

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jamesgeorge007/github-activity-readme@7028164baaaf6eb83ff9e846f91cbc3add58aa09 # v0.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
