name: Update Toolbox

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-toolbox:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: alexandre-abrioux/github-profile-toolbox@d9a61287fb67851f59477ea08fd11fbb52626daf # v1.3.1
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: "docs(readme): update toolbox"
          title: "docs(readme): update toolbox"
          body: "Toolbox updated by [github-profile-toolbox](https://github.com/alexandre-abrioux/github-profile-toolbox) GitHub action"
          branch: patch/toolbox
          sign-commits: true
          reviewers: ${{ github.actor }}
